### ISSUE TITLE
The version of scikit-learn

### ISSUE THREAD

**Issue by zivlzw** [LiyaoTang/contrastBoundary#35]
We built the tensorflow environment of CBL according to the configuration file, but the version of the library was not specified. Can you tell us the version of the scikit-learn, or what model environment the CBL uses?
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    trainer.train()
  File "/root/contrastBoundary-master/tensorflow/utils/trainer.py", line 66, in train
    g = GraphBuilder(config, verbose=self.verbose)
  File "/root/contrastBoundary-master/tensorflow/utils/tf_graph_builder.py", line 37, in __init__
    dataset = self.get_dataset(config, verbose)
  File "/root/contrastBoundary-master/tensorflow/models/../datasets/tf_s3dis_dataset.py", line 108, in __init__
    self.load_subsampled_clouds(config.first_subsampling_dl, verbose=verbose)
  File "/root/contrastBoundary-master/tensorflow/models/../datasets/tf_s3dis_dataset.py", line 245, in load_subsampled_clouds
    search_tree = pickle.load(f)
AttributeError: Can't get attribute 'EuclideanDistance64' on <module 'sklearn.metrics._dist_metrics' from '/root/miniconda3/envs/cbl/lib/python3.7/site-packages/sklearn/metrics/_dist_metrics.cpython-37m-x86_64-linux-gnu.so'>

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest.
Please try with scikit-learn<1 and see if the error persists.

Best,
Liyao
