### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by wxy127** [LiyaoTang/contrastBoundary#39]
Traceback (most recent call last):
  File "exp/s3dis/origin_multi-Ua-concat-latent_contrast-Ua-softnn-latent-label-l2-w.1/test.py", line 28, in <module>
    from model.basic_operators import _eps, _inf
  File "/root/autodl-fs/contrastBoundary-master/pytorch/model/basic_operators.py", line 4, in <module>
    from lib.pointops.functions import pointops
  File "/root/autodl-fs/contrastBoundary-master/pytorch/lib/pointops/functions/pointops.py", line 7, in <module>
    import pointops_cuda
ModuleNotFoundError: No module named 'pointops_cuda'

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest, and sorry for the late reply.

It seems that it is an error from the point-transformer backbone. Could you verify that if you have followed the instructions from the original point-transformer repo?

Please follow their instructions, and ensure that you can compile the pointops for point-transformer and run their demo successfully.

Best.
