### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by GitHub-HeZY** [LiyaoTang/contrastBoundary#44]
Hi. Thanks for your awesome work.
[train-20241202_194410.log](https://github.com/user-attachments/files/17977937/train-20241202_194410.log)

Use: export CUDA_LAUNCH_BLOCKING=1
I configured the environment according to pointTransformer, and there was no error in training.
But an error occurred when training your code:

/opt/conda/conda-bld/pytorch_1623448265233/work/aten/src/ATen/native/cuda/IndexKernel.cu:97: operator(): block: [119,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/nn/functional.py:652: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448265233/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1623448265233/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:158, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
/home/hzy/miniconda3/envs/pt/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "exp/s3dis/origin_multi-Ua-concat-latent_contrast-Ua-softnn-latent-label-l2-w.1/train.py", line 452, in <module>
    main()
  File "exp/s3dis/origin_multi-Ua-concat-latent_contrast-Ua-softnn-latent-label-l2-w.1/train.py", line 126, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/hzy/model/contrastBoundary/pytorch/exp/s3dis/origin_multi-Ua-concat-latent_contrast-Ua-softnn-latent-label-l2-w.1/train.py", line 261, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch)
  File "/home/hzy/model/contrastBoundary/pytorch/exp/s3dis/origin_multi-Ua-concat-latent_contrast-Ua-softnn-latent-label-l2-w.1/train.py", line 323, in train
    loss = criterion(output, target, stage_list)
  File "/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hzy/model/contrastBoundary/pytorch/model/pointtransformer_seg.py", line 24, in forward
    loss_list += self.contrast_head(output, target, stage_list)
  File "/home/hzy/miniconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hzy/model/contrastBoundary/pytorch/model/heads.py", line 251, in forward
    loss = self.main_contrast(n, i, stage_list, target)
  File "/home/hzy/model/contrastBoundary/pytorch/model/heads.py", line 191, in point_contrast
    labels = get_subscene_label(n, i, stage_list, target, self.nstride, self.config.num_classes)  # (m, ncls) - distribution / onehot
  File "/home/hzy/model/contrastBoundary/pytorch/model/basic_operators.py", line 14, in get_subscene_label
    return get_subscene_features(stage_n, stage_i, stage_list, x, nstride, **kwargs)
  File "/home/hzy/model/contrastBoundary/pytorch/model/basic_operators.py", line 49, in get_subscene_features
    x = x[neighbor_idx, :].view(p_to.shape[0], kr, x.shape[1]) # (m, kr, ncls)
RuntimeError: CUDA error: device-side assert triggered

/home/hzy/miniconda3/envs/pt/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/home/hzy/miniconda3/envs/pt/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by jianuo1128** [comment]
Hello, may I ask how you solved this problem @GitHub-HeZY
